'use client'

import { useMemo, useState } from 'react'
import {
  Archive, Bell, ChevronDown, ChevronLeft, ChevronRight, Clock3, HelpCircle, Inbox,
  Mail, Menu, MoreVertical, Pencil, RefreshCw, Search, Send, Settings, Star,
  Tag, Trash2, Users, Video, X, Reply, Printer, Forward, Check, SlidersHorizontal,
  ExternalLink, PanelLeft, Minimize2, Maximize2, Paperclip, Smile, Image as ImageIcon,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

type MailItem = { id: number; sender: string; initials: string; subject: string; preview: string; time: string; label?: string; unread?: boolean; starred?: boolean; avatar: string; folder?: string }

const seedMail: MailItem[] = [
  { id: 1, sender: 'Figma', initials: 'F', subject: 'Your team is growing', preview: 'A quick update on your Figma workspace and the latest collaboration features.', time: '10:42 AM', label: 'Updates', unread: true, starred: true, avatar: 'bg-rose-200 text-rose-800' },
  { id: 2, sender: 'Alex Morgan', initials: 'AM', subject: 'Re: Q4 planning notes', preview: 'Thanks for pulling this together. I added a few thoughts to the doc for our review.', time: '9:18 AM', unread: true, avatar: 'bg-sky-200 text-sky-800' },
  { id: 3, sender: 'The Morning', initials: 'TM', subject: 'The stories shaping your day', preview: 'Good morning. Here are today’s top stories, selected for you.', time: '8:05 AM', label: 'Newsletters', avatar: 'bg-amber-200 text-amber-800' },
  { id: 4, sender: 'Notion', initials: 'N', subject: 'You have been invited to a workspace', preview: 'Jamie invited you to join the Product Studio workspace.', time: 'Yesterday', label: 'Social', avatar: 'bg-slate-200 text-slate-800' },
  { id: 5, sender: 'Loom', initials: 'L', subject: 'Your weekly workspace recap', preview: 'See what your team has been watching and sharing this week.', time: 'Yesterday', avatar: 'bg-violet-200 text-violet-800' },
  { id: 6, sender: 'Dribbble', initials: 'D', subject: 'Fresh inspiration for your inbox', preview: 'A collection of delightful product details from the design community.', time: 'Jun 10', label: 'Promotions', avatar: 'bg-pink-200 text-pink-800' },
  { id: 7, sender: 'Taylor Kim', initials: 'TK', subject: 'Lunch next week?', preview: 'Are you free Tuesday or Wednesday? There is a new spot near the studio.', time: 'Jun 10', unread: true, avatar: 'bg-emerald-200 text-emerald-800' },
  { id: 8, sender: 'GitHub', initials: 'GH', subject: 'Security alert for your account', preview: 'A new sign-in was detected on your GitHub account.', time: 'Jun 9', label: 'Updates', avatar: 'bg-orange-200 text-orange-800' },
]

const folders = [{ icon: Inbox, label: 'Inbox' }, { icon: Star, label: 'Starred' }, { icon: Clock3, label: 'Snoozed' }, { icon: Send, label: 'Sent' }, { icon: Mail, label: 'Drafts' }]
const labels = ['Work', 'Travel', 'Receipts']

export function GmailClone() {
  const [mail, setMail] = useState(seedMail)
  const [query, setQuery] = useState('')
  const [selected, setSelected] = useState<number[]>([])
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [composeOpen, setComposeOpen] = useState(false)
  const [composeMinimized, setComposeMinimized] = useState(false)
  const [activeFolder, setActiveFolder] = useState('Inbox')
  const [category, setCategory] = useState('Primary')
  const [openMessage, setOpenMessage] = useState<MailItem | null>(null)
  const [panel, setPanel] = useState<'help' | 'settings' | 'apps' | 'profile' | null>(null)
  const [notice, setNotice] = useState('')
  const [draft, setDraft] = useState({ to: '', subject: '', body: '' })

  const showNotice = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(''), 2200) }
  const filteredMail = useMemo(() => mail.filter((item) => {
    const matchesQuery = `${item.sender} ${item.subject} ${item.preview}`.toLowerCase().includes(query.toLowerCase())
    const matchesFolder = activeFolder === 'Inbox' || (activeFolder === 'Starred' && item.starred) || (activeFolder === 'Drafts' && item.id === 5) || (activeFolder === 'Sent' && item.id === 2) || labels.includes(activeFolder)
    const matchesCategory = category === 'Primary' || item.label === category || (category === 'Social' && item.label === 'Social') || (category === 'Promotions' && item.label === 'Promotions')
    return matchesQuery && matchesFolder && matchesCategory
  }), [mail, query, activeFolder, category])

  const toggleSelected = (id: number) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const toggleStar = (id: number) => setMail((current) => current.map((item) => item.id === id ? { ...item, starred: !item.starred } : item))
  const mutateSelected = (action: 'archive' | 'delete' | 'read') => {
    if (!selected.length) return showNotice('Select at least one message')
    if (action === 'delete' || action === 'archive') setMail((current) => current.filter((item) => !selected.includes(item.id)))
    else setMail((current) => current.map((item) => selected.includes(item.id) ? { ...item, unread: false } : item))
    setSelected([]); showNotice(action === 'read' ? 'Marked as read' : action === 'archive' ? 'Conversation archived' : 'Conversation moved to Trash')
  }
  const openDetail = (item: MailItem) => { setOpenMessage(item); setMail((current) => current.map((entry) => entry.id === item.id ? { ...entry, unread: false } : entry)) }
  const chooseFolder = (label: string) => { setActiveFolder(label); setSelected([]); setOpenMessage(null); setSidebarOpen(false) }

  return <main className="flex min-h-screen bg-background text-foreground">
    <aside className={cn('fixed inset-y-0 left-0 z-30 flex w-64 -translate-x-full flex-col border-r bg-sidebar p-3 transition-transform lg:static lg:translate-x-0', sidebarOpen && 'translate-x-0')}>
      <div className="flex h-16 items-center gap-3 px-3 text-xl font-medium tracking-tight"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><span className="text-lg font-bold">M</span></div><span>Mail</span><Button variant="ghost" size="icon" className="ml-auto lg:hidden" onClick={() => setSidebarOpen(false)} aria-label="Close navigation"><X /></Button></div>
      <Button onClick={() => { setComposeOpen(true); setComposeMinimized(false) }} className="mb-5 h-14 w-fit gap-3 rounded-2xl px-5 shadow-sm"><Pencil data-icon="inline-start" />Compose</Button>
      <nav className="flex flex-col gap-1" aria-label="Mail folders">{folders.map(({ icon: Icon, label }) => <button key={label} onClick={() => chooseFolder(label)} className={cn('flex items-center gap-4 rounded-full px-4 py-2 text-sm transition-colors hover:bg-sidebar-accent', activeFolder === label && 'bg-sidebar-accent font-semibold')}><Icon className="size-4" /><span>{label}</span>{label === 'Inbox' && <span className="ml-auto text-xs font-semibold">6</span>}</button>)}</nav>
      <div className="mt-6 flex flex-col gap-1 border-t pt-4"><p className="px-4 pb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Labels</p>{labels.map((label) => <button key={label} onClick={() => chooseFolder(label)} className={cn('flex items-center gap-4 rounded-full px-4 py-2 text-sm hover:bg-sidebar-accent', activeFolder === label && 'bg-sidebar-accent font-semibold')}><Tag className="size-4" />{label}</button>)}</div>
      <div className="mt-auto flex items-center gap-3 rounded-xl border bg-card p-3"><button onClick={() => setPanel(panel === 'profile' ? null : 'profile')} className="grid size-9 place-items-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">JD</button><div className="min-w-0"><p className="truncate text-sm font-medium">Jordan Davis</p><p className="truncate text-xs text-muted-foreground">jordan@studio.co</p></div></div>
    </aside>
    {sidebarOpen && <button className="fixed inset-0 z-20 bg-foreground/20 lg:hidden" onClick={() => setSidebarOpen(false)} aria-label="Close navigation overlay" />}
    <section className="flex min-w-0 flex-1 flex-col">
      <header className="relative flex h-20 items-center gap-3 border-b px-4 md:px-6"><Button variant="ghost" size="icon" onClick={() => setSidebarOpen(true)} className="lg:hidden" aria-label="Open navigation"><Menu /></Button><div className="relative flex min-w-0 max-w-2xl flex-1 items-center"><Search className="absolute left-4 size-5 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search mail" className="h-12 w-full rounded-full bg-muted pl-12 pr-4 text-sm outline-none ring-ring transition focus:ring-2" /><Button variant="ghost" size="icon" className="absolute right-2" aria-label="Search options" onClick={() => showNotice('Search options opened')}><SlidersHorizontal /></Button></div><div className="hidden items-center gap-1 sm:flex"><Button variant="ghost" size="icon" aria-label="Help" onClick={() => setPanel(panel === 'help' ? null : 'help')}><HelpCircle /></Button><Button variant="ghost" size="icon" aria-label="Settings" onClick={() => setPanel(panel === 'settings' ? null : 'settings')}><Settings /></Button><Button variant="ghost" size="icon" aria-label="Apps" onClick={() => setPanel(panel === 'apps' ? null : 'apps')}><Users /></Button></div><button onClick={() => setPanel(panel === 'profile' ? null : 'profile')} className="grid size-9 shrink-0 place-items-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">JD</button>
        {panel && <div className="absolute right-4 top-16 z-40 w-72 rounded-xl border bg-popover p-4 text-popover-foreground shadow-xl"><div className="mb-3 flex items-center justify-between"><p className="font-semibold">{panel === 'help' ? 'Help & support' : panel === 'settings' ? 'Quick settings' : panel === 'apps' ? 'Google apps' : 'Account'}</p><Button variant="ghost" size="icon" className="size-7" onClick={() => setPanel(null)} aria-label="Close panel"><X /></Button></div>{panel === 'help' && <div className="flex flex-col gap-3 text-sm"><button className="text-left hover:underline" onClick={() => showNotice('Help center opened')}>Help Center</button><button className="text-left hover:underline" onClick={() => showNotice('Feedback form opened')}>Send feedback</button></div>}{panel === 'settings' && <div className="flex flex-col gap-3 text-sm"><label className="flex items-center justify-between">Density <select className="rounded border bg-background p-1"><option>Default</option><option>Comfortable</option></select></label><label className="flex items-center justify-between">Reading pane <input type="checkbox" /></label><button className="text-left text-primary hover:underline" onClick={() => showNotice('All settings opened')}>See all settings</button></div>}{panel === 'apps' && <div className="grid grid-cols-3 gap-3 text-center text-xs"><button onClick={() => showNotice('Calendar opened')} className="rounded-lg p-3 hover:bg-muted"><Bell className="mx-auto mb-1" />Calendar</button><button onClick={() => showNotice('Meet opened')} className="rounded-lg p-3 hover:bg-muted"><Video className="mx-auto mb-1" />Meet</button><button onClick={() => showNotice('Drive opened')} className="rounded-lg p-3 hover:bg-muted"><ExternalLink className="mx-auto mb-1" />Drive</button></div>}{panel === 'profile' && <div className="flex flex-col gap-3 text-sm"><p>jordan@studio.co</p><button className="rounded-lg border px-3 py-2 text-left hover:bg-muted" onClick={() => showNotice('Account switcher opened')}>Switch account</button><button className="rounded-lg border px-3 py-2 text-left hover:bg-muted" onClick={() => showNotice('Signed out of mock account')}>Sign out</button></div>}</div>}
      </header>
      <div className="flex items-center justify-between px-4 py-4 md:px-8"><div className="flex items-center gap-1"><Button variant="outline" size="icon" aria-label="Select all" onClick={() => setSelected(selected.length === filteredMail.length ? [] : filteredMail.map((item) => item.id))}><span className={cn('size-4 rounded-sm border-2', selected.length === filteredMail.length && filteredMail.length > 0 && 'bg-primary')} /></Button><Button variant="ghost" size="icon" aria-label="Refresh" onClick={() => showNotice('Inbox refreshed')}><RefreshCw /></Button>{selected.length > 0 && <><Button variant="ghost" size="icon" aria-label="Archive selected" onClick={() => mutateSelected('archive')}><Archive /></Button><Button variant="ghost" size="icon" aria-label="Delete selected" onClick={() => mutateSelected('delete')}><Trash2 /></Button><Button variant="ghost" size="icon" aria-label="Mark selected read" onClick={() => mutateSelected('read')}><Mail /></Button></>}<Button variant="ghost" size="icon" aria-label="More actions" onClick={() => showNotice('More actions opened')}><MoreVertical /></Button></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><span>1–{filteredMail.length} of 1,248</span><Button variant="ghost" size="icon" aria-label="Previous page" onClick={() => showNotice('Already on first page')}><ChevronLeft /></Button><Button variant="ghost" size="icon" aria-label="Next page" onClick={() => showNotice('Next page loaded')}><ChevronRight /></Button></div></div>
      <div className="mx-3 overflow-hidden rounded-xl border bg-card md:mx-8"><div className="flex items-center gap-8 border-b px-5 pt-3 text-sm font-medium"><button onClick={() => setCategory('Primary')} className={cn('flex items-center gap-2 border-b-2 pb-3', category === 'Primary' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground')}><Inbox className="size-4" />Primary</button><button onClick={() => setCategory('Social')} className={cn('hidden items-center gap-2 border-b-2 pb-3 sm:flex', category === 'Social' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground')}><Users className="size-4" />Social</button><button onClick={() => setCategory('Promotions')} className={cn('hidden items-center gap-2 border-b-2 pb-3 sm:flex', category === 'Promotions' ? 'border-primary text-primary' : 'border-transparent text-muted-foreground')}><Tag className="size-4" />Promotions</button></div>
        {filteredMail.length ? filteredMail.map((item) => <div key={item.id} className={cn('group flex min-h-16 items-center gap-3 border-b px-4 py-3 last:border-0 hover:bg-muted/60', item.unread && 'bg-muted/30 font-semibold')}><button onClick={() => toggleSelected(item.id)} className="grid size-5 shrink-0 place-items-center" aria-label={`Select ${item.subject}`}><span className={cn('size-4 rounded-sm border', selected.includes(item.id) && 'border-primary bg-primary')} /></button><button onClick={() => toggleStar(item.id)} aria-label={`${item.starred ? 'Unstar' : 'Star'} ${item.subject}`}><Star className={cn('size-5 text-muted-foreground', item.starred && 'fill-amber-400 text-amber-400')} /></button><button onClick={() => openDetail(item)} className="flex min-w-0 flex-1 flex-col gap-0.5 text-left md:flex-row md:items-center md:gap-4"><span className={cn('grid size-8 shrink-0 place-items-center rounded-full text-xs font-bold', item.avatar)}>{item.initials}</span><span className="w-32 shrink-0 truncate text-sm">{item.sender}</span><span className="min-w-0 truncate text-sm"><span>{item.subject}</span><span className="font-normal text-muted-foreground"> — {item.preview}</span></span></button>{item.label && <span className="hidden rounded-md bg-secondary px-2 py-1 text-[11px] font-medium text-secondary-foreground sm:inline-flex">{item.label}</span>}<span className="w-16 shrink-0 text-right text-xs text-muted-foreground">{item.time}</span><div className="hidden gap-1 group-hover:flex"><Button variant="ghost" size="icon" className="size-8" onClick={() => mutateSelected('archive')} aria-label={`Archive ${item.subject}`}><Archive /></Button><Button variant="ghost" size="icon" className="size-8" onClick={() => { setSelected([item.id]); mutateSelected('delete') }} aria-label={`Delete ${item.subject}`}><Trash2 /></Button></div></div>) : <div className="flex flex-col items-center gap-2 px-6 py-16 text-center"><Mail className="size-10 text-muted-foreground" /><p className="font-medium">No messages here</p><p className="text-sm text-muted-foreground">Try another folder, category, or search.</p><Button variant="outline" onClick={() => { setActiveFolder('Inbox'); setCategory('Primary'); setQuery('') }}>Return to inbox</Button></div>}
      </div>
      <footer className="flex items-center justify-between px-4 py-5 text-xs text-muted-foreground md:px-8"><span>Storage used: 4.2 GB of 15 GB</span><span className="hidden items-center gap-2 sm:flex"><Video className="size-4" />Meet is ready when you are</span></footer>
    </section>

    {openMessage && <div className="fixed inset-0 z-40 flex items-center justify-center bg-foreground/20 p-4"><article className="flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl border bg-card shadow-2xl"><div className="flex items-center justify-between border-b p-3"><Button variant="ghost" size="icon" onClick={() => setOpenMessage(null)} aria-label="Back to inbox"><ChevronLeft /></Button><div className="flex items-center gap-1"><Button variant="ghost" size="icon" onClick={() => { setSelected([openMessage.id]); mutateSelected('archive'); setOpenMessage(null) }} aria-label="Archive message"><Archive /></Button><Button variant="ghost" size="icon" onClick={() => { setSelected([openMessage.id]); mutateSelected('delete'); setOpenMessage(null) }} aria-label="Delete message"><Trash2 /></Button><Button variant="ghost" size="icon" onClick={() => showNotice('Message marked unread')} aria-label="Mark unread"><Mail /></Button><Button variant="ghost" size="icon" onClick={() => setOpenMessage(null)} aria-label="Close message"><X /></Button></div></div><div className="overflow-y-auto p-6"><h1 className="text-2xl font-semibold text-balance">{openMessage.subject}</h1><div className="mt-6 flex items-center gap-3"><div className={cn('grid size-10 place-items-center rounded-full text-sm font-bold', openMessage.avatar)}>{openMessage.initials}</div><div><p className="font-semibold">{openMessage.sender}</p><p className="text-xs text-muted-foreground">to Jordan Davis · {openMessage.time}</p></div><Button variant="ghost" size="icon" className="ml-auto" onClick={() => toggleStar(openMessage.id)} aria-label="Star message"><Star className={cn(openMessage.starred && 'fill-amber-400 text-amber-400')} /></Button></div><p className="mt-8 max-w-2xl whitespace-pre-line text-sm leading-7">{openMessage.preview}\n\nThanks for taking a look. Let’s keep the momentum going and sync on the next steps together.\n\nBest,\n{openMessage.sender}</p><div className="mt-8 flex gap-2"><Button variant="outline" onClick={() => { setComposeOpen(true); setDraft({ to: `${openMessage.sender} <hello@example.com>`, subject: `Re: ${openMessage.subject}`, body: '' }); setOpenMessage(null) }}><Reply data-icon="inline-start" />Reply</Button><Button variant="outline" onClick={() => showNotice('Forward composer opened')}><Forward data-icon="inline-start" />Forward</Button><Button variant="ghost" size="icon" aria-label="Print message" onClick={() => showNotice('Print dialog opened')}><Printer /></Button></div></div></article></div>}

    {composeOpen && <div className={cn('fixed bottom-0 right-4 z-50 w-[calc(100%-2rem)] max-w-md overflow-hidden rounded-t-xl border bg-card shadow-2xl', composeMinimized && 'w-72')}><div className="flex items-center justify-between bg-muted px-4 py-3 text-sm font-semibold"><span>New Message</span><div className="flex items-center gap-1"><Button variant="ghost" size="icon" className="size-7" onClick={() => setComposeMinimized(!composeMinimized)} aria-label={composeMinimized ? 'Maximize compose' : 'Minimize compose'}>{composeMinimized ? <Maximize2 /> : <Minimize2 />}</Button><Button variant="ghost" size="icon" className="size-7" onClick={() => setComposeOpen(false)} aria-label="Close compose"><X /></Button></div></div>{!composeMinimized && <div className="flex flex-col"><input value={draft.to} onChange={(e) => setDraft({ ...draft, to: e.target.value })} className="border-b bg-transparent px-4 py-3 text-sm outline-none" placeholder="Recipients" /><input value={draft.subject} onChange={(e) => setDraft({ ...draft, subject: e.target.value })} className="border-b bg-transparent px-4 py-3 text-sm outline-none" placeholder="Subject" /><textarea value={draft.body} onChange={(e) => setDraft({ ...draft, body: e.target.value })} className="min-h-40 resize-none bg-transparent px-4 py-3 text-sm outline-none" placeholder="Write your message..." /><div className="flex items-center justify-between border-t p-3"><div className="flex items-center gap-1"><Button variant="ghost" size="icon" aria-label="Attach file" onClick={() => showNotice('Attachment picker opened')}><Paperclip /></Button><Button variant="ghost" size="icon" aria-label="Add emoji"><Smile /></Button><Button variant="ghost" size="icon" aria-label="Insert image"><ImageIcon /></Button></div><div className="flex items-center gap-2"><Button variant="ghost" size="icon" aria-label="Discard draft" onClick={() => { setComposeOpen(false); setDraft({ to: '', subject: '', body: '' }); showNotice('Draft discarded') }}><Trash2 /></Button><Button onClick={() => { setComposeOpen(false); setDraft({ to: '', subject: '', body: '' }); showNotice('Message sent') }}>Send</Button></div></div></div>}</div>}
    {notice && <div role="status" className="fixed bottom-5 left-1/2 z-[60] flex -translate-x-1/2 items-center gap-2 rounded-lg bg-foreground px-4 py-3 text-sm text-background shadow-lg"><Check className="size-4" />{notice}</div>}
  </main>
}
